apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
  namespace: tag-api-namespace
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8181"
        prometheus.io/scrape: "true"
      labels:
        app: api
    spec:
      containers:
      - image: n1c0l4stournier/springboot.rest:latest
        imagePullPolicy: Always
        name: springboot-rest
        ports:
          - containerPort: 8181
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mysql-database
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mysql-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql-password
        - name: DB_URL
          value: mysql-service